Repository 10up/safe-redirect-manager, pull requests merged in 2019-10, with the labels that each got.

#154 check if notes are empty to update or delete postmeta
  inc/classes/class-srm-post-type.php
Labels: enhancement

#182 Improve path matching for wildcards and query parameters
  .travis.yml
  inc/classes/class-srm-redirect.php
  phpunit.xml.dist
  tests/php/test-core.php
Labels: bug

#178 Add user capability checking later
  inc/classes/class-srm-post-type.php
Labels: bug

#185 check if notes are empty to update or delete postmeta
  inc/classes/class-srm-post-type.php
Labels: bug

#181 Create CHANGELOG.md
  CHANGELOG.md
Labels: documentation
