Repository 10up/safe-redirect-manager, pull requests merged in 2020-11, with the labels that each got.

#196 Fix/189 ignore query params
  inc/classes/class-srm-redirect.php
  tests/php/test-core.php
Labels: enhancement

#203 Fix: Use proper hook for setting up SRM_Redirect
  inc/classes/class-srm-redirect.php
Labels: bug

#224 Add: srm_redirect_only_on_404 documentation
  README.md
Labels: documentation

#215 Add 410 support, make status codes filterable
  README.md
  inc/classes/class-srm-post-type.php
  inc/functions.php
  readme.txt
Labels: enhancement
